### ISSUE TITLE
constant not defined : _MS_WGFILEMANAGER_DIRECTORY_ID

### ISSUE THREAD

**Issue by JJDai54** [XoopsModules25x/wgfilemanager#12]
file : \wgfilemanager\templates\admin\wgfilemanager_admin_directory.tpl
Line 12 : 
_MS_WGFILEMANAGER_DIRECTORY_ID
instead of
_MA_WGFILEMANAGER_DIRECTORY_ID
-------------------------------
_AM_WGFILEMANAGER_FORM_ACTION  is not defined

**Comment by ggoffy** [comment]
fixed with https://github.com/XoopsModules25x/wgfilemanager/pull/15

thank you for testing and reporting
