### ISSUE TITLE
module preferences

### ISSUE THREAD

**Issue by JJDai54** [XoopsModules25x/wgfilemanager#14]
Unable to edit module preferences.
yet permissions are correct.

**Comment by ggoffy** [comment]
do not have the problem. did you get any error? which XOOPS and PHP version?

**Comment by JJDai54** [comment]
xoopd 2.5.11
php 8.2.13
mysql 8.2.0

![2024-08-23 09 23 26](https://github.com/user-attachments/assets/8cd81430-0fa8-4afe-ac53-5e863e7b4416)

PS : I have to go away for a week, when I get back I will try to find out what the problem is.

**Comment by JJDai54** [comment]
I reinstalled a xoops 2.5.11-stable, and there is no problème, may be it's my old installation
